const animals = [
  {
    name: 'Adelie Penguin',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Aves',
      order: 'Sphenisciformes',
      family: 'Spheniscidae',
      genus: 'Pygoscelis',
      scientific_name: 'Pygoscelis adeliae'
    },
    locations: ['Antarctica', 'Asia', 'Eurasia', 'Ocean'],
    characteristics: {
      prey: 'Krill, Fish, Squid',
      name_of_young: 'Chicks',
      group_behavior: 'Colony',
      estimated_population_size: '5 million',
      biggest_threat: 'Rapid ice melt',
      most_distinctive_feature: 'Small white circle around each eye',
      wingspan: '35cm - 70cm (14in - 27.5in)',
      incubation_period: '2 months',
      age_of_fledgling: '90 days',
      habitat: 'Antarctic land and ocean',
      predators: 'Leopard Seal, Skua Gull, Killer Whale',
      diet: 'Carnivore',
      lifestyle: 'Diurnal',
      common_name: 'Adelie Penguin',
      number_of_species: '1',
      location: 'Coastal Antarctica',
      average_clutch_size: '2',
      slogan: 'Eats up to 2kg of food per day!',
      group: 'Bird',
      skin_type: 'Feathers',
      top_speed: '45 mph',
      lifespan: '10 - 20 years',
      weight: '3kg - 6kg (7lbs - 13lbs)',
      height: '40cm - 75cm (16in - 30in)',
      age_of_sexual_maturity: '2 - 3 years'
    }
  },
  {
    name: 'African Penguin',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Aves',
      order: 'Sphenisciformes',
      family: 'Spheniscidae',
      genus: 'Spheniscus',
      scientific_name: 'Spheniscus demersus'
    },
    locations: ['Africa', 'Ocean'],
    characteristics: {
      prey: 'Fish, Squid, Crustaceans',
      name_of_young: 'Chick',
      group_behavior: 'Colony',
      estimated_population_size: '140,000',
      biggest_threat: 'Habitat disruption',
      most_distinctive_feature: 'Pink glands above their eyes',
      other_names: 'Jackass Penguin',
      water_type: 'Salt',
      incubation_period: '40 days',
      age_of_fledgling: '3 - 5 months',
      habitat: 'Rocky Ocean Islands',
      predators: 'Sharks, Fur Seals, Gulls',
      diet: 'Carnivore',
      lifestyle: 'Diurnal',
      common_name: 'African Penguin',
      number_of_species: '1',
      location: 'south-west African coast',
      average_clutch_size: '2',
      slogan: 'The only penguin species in Africa!',
      group: 'Bird',
      color: 'GreyBlackWhite',
      skin_type: 'Feathers',
      top_speed: '12.4 mph',
      lifespan: '10 - 15 years',
      weight: '2kg - 5kg (4.4lbs - 11lbs)',
      height: '60cm - 68cm (24in - 27in)',
      age_of_sexual_maturity: '3 - 4 years'
    }
  },
  {
    name: 'Chinstrap Penguin',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Aves',
      order: 'Sphenisciformes',
      family: 'Spheniscidae',
      genus: 'Pygoscelis',
      scientific_name: 'Pygoscelis Antarcticus'
    },
    locations: ['Antarctica', 'Ocean'],
    characteristics: {
      main_prey: 'Krill, Fish, Shrimp',
      distinctive_feature:
        'White face and thin, black line that runs under the chin',
      habitat: 'Rocky Antarctic Islands',
      predators: 'Leopard Seal, Killer Whale, Sea Birds',
      diet: 'Carnivore',
      average_litter_size: '2',
      lifestyle: 'Colony',
      favorite_food: 'Krill',
      type: 'Bird',
      slogan: 'There are 7 million breeding pairs!',
      color: 'GreyBlackWhite',
      skin_type: 'Feathers',
      lifespan: '15 - 20 years',
      weight: '3kg - 6kg (6.6lbs - 13lbs)',
      height: '60cm - 68cm (24in - 27in)'
    }
  },
  {
    name: 'Crested Penguin',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Aves',
      order: 'Sphenisciformes',
      family: 'Spheniscidae',
      genus: 'Eudyptes',
      scientific_name: 'Eudyptes robustus'
    },
    locations: ['Ocean', 'Oceania'],
    characteristics: {
      main_prey: 'Krill, Fish, Shrimp',
      distinctive_feature: 'Red beak and bright yellow eyebrows',
      habitat: 'Rocky Antarctic Islands',
      predators: 'Leopard Seal, Killer Whale, Sharks',
      diet: 'Carnivore',
      average_litter_size: '2',
      lifestyle: 'Colony',
      favorite_food: 'Krill',
      type: 'Bird',
      slogan: 'Has long yellow eyebrows!',
      color: 'GreyYellowBlackWhite',
      skin_type: 'Feathers',
      lifespan: '15 - 20 years',
      weight: '3kg - 6kg (6.6lbs - 13lbs)',
      height: '60cm - 68cm (24in - 27in)'
    }
  },
  {
    name: 'Emperor Penguin',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Aves',
      order: 'Sphenisciformes',
      family: 'Spheniscidae',
      genus: 'Aptenodytes',
      scientific_name: 'Aptenodytes forsteri'
    },
    locations: ['Antarctica', 'Ocean'],
    characteristics: {
      prey: 'Fish, Krill, Squid',
      name_of_young: 'Chick',
      group_behavior: 'Colony',
      estimated_population_size: '200,000 breeding pairs',
      biggest_threat: 'Global warming',
      most_distinctive_feature: 'Bright yellow feathers on neck and ears',
      wingspan: '76cm - 89cm (30in - 35in)',
      incubation_period: '60 - 70 days',
      age_of_fledgling: '5 - 6 months',
      habitat: 'Compact sea-ice and ocean',
      predators: 'Southern Giant Petrol, Leopard Seal, Killer Whale',
      diet: 'Carnivore',
      lifestyle: 'Diurnal',
      common_name: 'Emperor Penguin',
      number_of_species: '1',
      location: 'Antarctica',
      average_clutch_size: '1',
      slogan: "The world's largest species of penguin!",
      group: 'Bird',
      color: 'YellowBlackWhiteOrange',
      skin_type: 'Feathers',
      top_speed: '15 mph',
      lifespan: '15 - 50 years',
      weight: '22kg - 45kg (49lbs - 99lbs)',
      height: '100cm - 120cm (39in - 47in)',
      age_of_sexual_maturity: '3 - 8 years'
    }
  },
  {
    name: 'Galapagos Penguin',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Aves',
      order: 'Sphenisciformes',
      family: 'Spheniscidae',
      genus: 'Spheniscus',
      scientific_name: 'Spheniscus Mendiculus'
    },
    locations: ['Ocean'],
    characteristics: {
      main_prey: 'Krill, Fish, Shrimp',
      distinctive_feature: 'Small body size and fully black head',
      habitat: 'Rocky Ocean Islands',
      predators: 'Leopard Seal, Killer Whale, Sharks',
      diet: 'Carnivore',
      average_litter_size: '2',
      lifestyle: 'Colony',
      favorite_food: 'Krill',
      type: 'Bird',
      slogan: 'Found around the Equator!',
      color: 'GreyBlackWhite',
      skin_type: 'Feathers',
      lifespan: '15 - 20 years',
      weight: '2kg - 4kg (4.4lbs - 8.8lbs)',
      height: '48cm - 50cm (19in - 20in)'
    }
  },
  {
    name: 'Gentoo Penguin',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Aves',
      order: 'Sphenisciformes',
      family: 'Spheniscidae',
      genus: 'Pygoscelis',
      scientific_name: 'Pygoscelis papua'
    },
    locations: ['Antarctica', 'Ocean'],
    characteristics: {
      main_prey: 'Krill, Fish, Shrimp',
      distinctive_feature: 'Small head with orange beak and feet',
      habitat: 'Rocky Antarctic Islands',
      predators: 'Leopard Seal, Killer Whale, Sharks',
      diet: 'Carnivore',
      average_litter_size: '2',
      lifestyle: 'Colony',
      favorite_food: 'Krill',
      type: 'Bird',
      slogan: 'Found throughout the sub-Antarctic!',
      color: 'GreyBlackWhiteOrange',
      skin_type: 'Feathers',
      lifespan: '15 - 20 years',
      weight: '4kg - 8kg (8.8lbs - 18lbs)',
      height: '51cm - 90cm (20in - 36in)'
    }
  },
  {
    name: 'Humboldt Penguin',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Aves',
      order: 'Sphenisciformes',
      family: 'Spheniscidae',
      genus: 'Spheniscus',
      scientific_name: 'Spheniscus humboldti'
    },
    locations: ['Ocean', 'South-America'],
    characteristics: {
      main_prey: 'Krill, Fish, Shrimp',
      distinctive_feature: 'Pink base of beak and black and white markings',
      habitat: 'Rocky Ocean Islands',
      predators: 'Leopard Seal, Killer Whale, Sharks',
      diet: 'Carnivore',
      average_litter_size: '2',
      lifestyle: 'Colony',
      favorite_food: 'Krill',
      type: 'Bird',
      slogan: 'Found on the South American coast!',
      color: 'GreyBlackWhite',
      skin_type: 'Feathers',
      lifespan: '15 - 20 years',
      weight: '2kg - 5kg (4.4lbs - 11lbs)',
      height: '60cm - 68cm (24in - 27in)'
    }
  },
  {
    name: 'King Penguin',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Aves',
      order: 'Sphenisciformes',
      family: 'Spheniscidae',
      genus: 'Aptenodytes',
      scientific_name: 'Aptenodytes patagonicus'
    },
    locations: ['Antarctica', 'Ocean'],
    characteristics: {
      main_prey: 'Krill, Fish, Shrimp',
      distinctive_feature: 'Large body size with yellow markings on head',
      habitat: 'Rocky Antarctic Islands',
      predators: 'Leopard Seal, Killer Whale, Sharks',
      diet: 'Carnivore',
      average_litter_size: '1',
      lifestyle: 'Colony',
      favorite_food: 'Krill',
      type: 'Bird',
      slogan: 'More than 2 million breeding pairs!',
      color: 'GreyYellowBlackWhite',
      skin_type: 'Feathers',
      lifespan: '15 - 20 years',
      weight: '11kg - 16kg (24lbs - 35lbs)',
      height: '60cm - 90cm (24in - 35in)'
    }
  },
  {
    name: 'Little Penguin',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Aves',
      order: 'Sphenisciformes',
      family: 'Spheniscidae',
      genus: 'Eudyptula',
      scientific_name: 'Eudyptula Minor'
    },
    locations: ['Ocean', 'Oceania'],
    characteristics: {
      main_prey: 'Krill, Fish, Shrimp',
      distinctive_feature: 'Small body size with blue/grey feathers',
      habitat: 'Rocky Antarctic Islands',
      predators: 'Leopard Seal, Killer Whale, Sharks',
      diet: 'Carnivore',
      average_litter_size: '2',
      lifestyle: 'Colony',
      favorite_food: 'Krill',
      type: 'Bird',
      slogan: 'The smallest species of penguin!',
      color: 'GreyBlueBlackWhite',
      skin_type: 'Feathers',
      lifespan: '10 - 20 years',
      weight: '1kg - 3kg (2.2lbs - 6.6lbs)',
      height: '35cm - 50cm (14in - 20in)'
    }
  },
  {
    name: 'Macaroni Penguin',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Aves',
      order: 'Sphenisciformes',
      family: 'Spheniscidae',
      genus: 'Eudyptes',
      scientific_name: 'Eudyptes Chrysolophus'
    },
    locations: ['Antarctica', 'Ocean'],
    characteristics: {
      main_prey: 'Fish, Squid, Crustaceans',
      wingspan: '80-100cm (31-39in)',
      habitat: 'Sea and ice-islands in Sub-Antarctica',
      predators: 'Leopard Seal, Killer Whale',
      diet: 'Carnivore',
      lifestyle: 'Colony',
      favorite_food: 'Fish',
      type: 'Bird',
      average_clutch_size: '2',
      slogan: 'Gather in colonies of up to 100,000 members!',
      color: 'BrownYellowBlackWhite',
      skin_type: 'Feathers',
      top_speed: '22 mph',
      lifespan: '15-20 years',
      weight: '3.2-6.4kg (7-14lbs)'
    }
  },
  {
    name: 'Magellanic Penguin',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Aves',
      order: 'Sphenisciformes',
      family: 'Spheniscidae',
      genus: 'Spheniscus',
      scientific_name: 'Spheniscus magellanicus'
    },
    locations: ['Ocean', 'South-America'],
    characteristics: {
      main_prey: 'Cuttlefish, Squid, Sardines',
      distinctive_feature: 'Black beak and small wings',
      habitat: 'Antarctic islands',
      predators: 'Sea Lion, Leopard Seal, Killer Whale',
      diet: 'Carnivore',
      average_litter_size: '2',
      lifestyle: 'Flock',
      favorite_food: 'Cuttlefish',
      type: 'Bird',
      slogan: 'Threatened by oil spills!',
      color: 'BrownGreyBlackWhite',
      skin_type: 'Feathers',
      top_speed: '22 mph',
      lifespan: '15 - 20 years',
      weight: '2.7kg - 6.5kg (5.9lbs - 14lbs)',
      length: '61cm - 76cm (24in - 30in)'
    }
  },
  {
    name: 'Penguin',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Aves',
      order: 'Sphenisciformes',
      family: 'Spheniscidae',
      scientific_name: 'Aptenodytes Forsteri'
    },
    locations: ['Antarctica', 'Ocean'],
    characteristics: {
      main_prey: 'Fish, Crabs, Squid',
      distinctive_feature: 'Short, sharp beak and slight webbed feet',
      wingspan: '60cm - 130cm (23.6in - 21in)',
      habitat: 'Cold seas and rocky land',
      predators: 'Leopard Seals, Sharks, Killer Whale',
      diet: 'Omnivore',
      lifestyle: 'Group',
      favorite_food: 'Fish',
      type: 'Bird',
      average_clutch_size: '1',
      slogan: "Spends 75% of it's time hunting for food!",
      color: 'GreyYellowBlackWhite',
      skin_type: 'Feathers',
      top_speed: '40 mph',
      lifespan: '20 - 30 years',
      weight: '1kg - 35kg (2.2lbs - 75lbs)',
      height: '40cm - 110cm (15.7in - 43in)'
    }
  },
  {
    name: 'Rockhopper Penguin',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Aves',
      order: 'Sphenisciformes',
      family: 'Spheniscidae',
      genus: 'Eudyptes',
      scientific_name: 'Eudyptes chrysocome'
    },
    locations: ['Antarctica', 'Ocean', 'Oceania', 'South-America'],
    characteristics: {
      main_prey: 'Krill, Fish, Shrimp',
      distinctive_feature: 'Red beaks and eyes, with yellow head feathers',
      habitat: 'Rocky Antarctic Islands',
      predators: 'Leopard Seal, Killer Whale, Sharks',
      diet: 'Carnivore',
      average_litter_size: '2',
      lifestyle: 'Colony',
      favorite_food: 'Krill',
      type: 'Bird',
      slogan: 'There are 3 different species!',
      color: 'GreyBlackWhite',
      skin_type: 'Feathers',
      lifespan: '15 - 20 years',
      weight: '2kg - 5kg (4.4lbs - 11lbs)',
      height: '45cm - 58cm (18in - 23in)'
    }
  },
  {
    name: 'Royal Penguin',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Aves',
      order: 'Sphenisciformes',
      family: 'Spheniscidae',
      genus: 'Eudyptes',
      scientific_name: 'Eudyptes schlegeli'
    },
    locations: ['Antarctica', 'Ocean'],
    characteristics: {
      main_prey: 'Krill, Fish, Shrimp',
      distinctive_feature: 'Orange beak with yellow feathers on head',
      habitat: 'Rocky Antarctic Islands',
      predators: 'Leopard Seal, Killer Whale, Sharks',
      diet: 'Carnivore',
      average_litter_size: '2',
      lifestyle: 'Colony',
      favorite_food: 'Krill',
      type: 'Bird',
      slogan: 'Can reach speeds of 20mph!',
      color: 'GreyYellowBlackWhite',
      skin_type: 'Feathers',
      lifespan: '15 - 20 years',
      weight: '3kg - 6kg (6.6lbs - 13lbs)',
      height: '60cm - 68cm (24in - 27in)'
    }
  },
  {
    name: 'Yellow-Eyed Penguin',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Aves',
      order: 'Sphenisciformes',
      family: 'Spheniscidae',
      genus: 'Megadyptes',
      scientific_name: 'Megadyptes antipodes'
    },
    locations: ['Ocean', 'Oceania'],
    characteristics: {
      main_prey: 'Krill, Fish, Shrimp',
      distinctive_feature: 'Bright yellow head-band and pink coloured feet',
      habitat: 'Rocky Antarctic Islands',
      predators: 'Leopard Seal, Killer Whale, Sharks',
      diet: 'Carnivore',
      average_litter_size: '2',
      lifestyle: 'Colony',
      favorite_food: 'Krill',
      type: 'Bird',
      slogan: 'The rarest species of penguin!',
      color: 'BrownGreyYellowBlackWhite',
      skin_type: 'Feathers',
      lifespan: '10 - 20 years',
      weight: '5kg - 8kg (11lbs - 18lbs)',
      height: '60cm - 75cm (24in - 30in)'
    }
  },
  {
    name: 'Giraffe',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Artiodactyla',
      family: 'Giraffidae',
      genus: 'Giraffa',
      scientific_name: 'Giraffa camelopardalis'
    },
    locations: ['Africa'],
    characteristics: {
      prey: 'Leaves, Fruits, Seeds',
      name_of_young: 'Calf',
      group_behavior: 'Herd',
      estimated_population_size: 'Stable',
      biggest_threat: 'Hunting and habitat loss',
      most_distinctive_feature: 'Elongated neck and unique patterned coat',
      gestation_period: '457 days',
      habitat: 'Open woodland and savannah',
      diet: 'Herbivore',
      average_litter_size: '1',
      lifestyle: 'Diurnal',
      common_name: 'Giraffe',
      number_of_species: '9',
      location: 'sub-Saharan Africa',
      slogan: 'Long, black tongue can grow to 18 inches long!',
      group: 'Mammal',
      color: 'BrownRedBlackWhiteTan',
      skin_type: 'Hair',
      top_speed: '30 mph',
      lifespan: '20 - 25 years',
      weight: '550kg - 1,930kg (1,200lbs - 4,200lbs)',
      height: '4m - 6m (13ft - 20ft)',
      age_of_sexual_maturity: '3.5 - 4.5 years',
      age_of_weaning: '13 months'
    }
  },
  {
    name: 'Alpine Goat',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Artiodactyla',
      family: 'Bovidae',
      genus: 'Capra',
      scientific_name: 'Capra aegagrus hircus'
    },
    locations: ['Europe', 'North-America'],
    characteristics: {
      name_of_young: 'Kids',
      group_behavior: 'Herd',
      biggest_threat: 'Habitat reduction',
      most_distinctive_feature: 'Tall, slightly curved horns',
      other_names: 'French Alpine, British Alpine, Rock Alpine',
      gestation_period: '155 days',
      litter_size: '1.75',
      habitat: 'Domestic, mountains',
      predators: 'Wolves, mountain lions, bobcats, and other carnivores',
      diet: 'Herbivore',
      favorite_food: 'Grass, vegetation',
      type: 'Mammal',
      common_name: 'Alpine goat',
      color: 'BrownGreyBlackWhite',
      skin_type: 'Hair',
      top_speed: '15 mph',
      lifespan: '15-18 years',
      weight: '135-175 lbs',
      height: '32 inches',
      age_of_sexual_maturity: '2 years',
      age_of_weaning: '8 weeks'
    }
  },
  {
    name: 'American Pygmy Goat',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Artiodactyla',
      family: 'Bovidae',
      genus: 'Capra',
      scientific_name: 'Capra aegagrus hircus'
    },
    locations: ['North-America'],
    characteristics: {
      name_of_young: 'Kid',
      group_behavior: 'Herd',
      most_distinctive_feature: 'Small size',
      other_names: 'Pygmy Goat, African Pygmy, Dwarf Cameroon',
      gestation_period: '5 months',
      litter_size: '1-4',
      habitat: 'Rocky terrain, Hillsides, Plains, Farmland',
      predators: 'dogs, coyotes, bobcats',
      diet: 'Herbivore',
      favorite_food: 'Greens and grains',
      type: 'Mammal',
      common_name: 'Pygmy goat',
      location: 'United States',
      color: 'GreyBlackWhiteCaramel',
      skin_type: 'Fur',
      lifespan: '8-12 years',
      weight: '30-90 lbs',
      height: '15-20 inches',
      length: '18-33 inches',
      age_of_sexual_maturity: '2-4 months',
      age_of_weaning: '8 weeks'
    }
  },
  {
    name: 'Angora Goat',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Artiodactyla',
      family: 'Bovidae',
      genus: 'Capra',
      scientific_name: 'Capra aegagrus hircus'
    },
    locations: [
      'Africa',
      'Asia',
      'Eurasia',
      'Europe',
      'North-America',
      'Oceania',
      'South-America'
    ],
    characteristics: {
      name_of_young: 'Kid',
      group_behavior: 'Herd',
      biggest_threat: 'Coyotes',
      most_distinctive_feature: 'Angora goats produce mohair fiber.',
      other_names: 'Angoras',
      gestation_period: '150 days',
      litter_size: '1',
      habitat: 'Farms',
      predators: 'Coyotes',
      diet: 'Herbivore',
      type: 'Mammals',
      common_name: 'Angora goats',
      number_of_species: '1',
      location: 'Worldwide',
      group: 'Flock',
      color: 'RedBlackWhite',
      skin_type: 'Hair',
      lifespan: '10 years',
      weight: '82kg-100kg (180lbs-220lbs)',
      height: '91cm-122cm(38in-48in)',
      length: '127cm(50in)',
      age_of_sexual_maturity: '6-7 months',
      age_of_weaning: '4-6 months'
    }
  },
  {
    name: 'Cashmere Goat',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Artiodactyla',
      family: 'Bovidae',
      genus: 'Capra',
      scientific_name: 'Capra aegagrus hircus'
    },
    locations: ['Asia', 'Europe', 'North-America', 'Oceania'],
    characteristics: {
      name_of_young: 'Kid',
      group_behavior: 'Sociable',
      estimated_population_size: '700 million',
      biggest_threat: 'Coyotes, disease',
      most_distinctive_feature: 'Soft, downy fibers of their undercoats',
      gestation_period: 'Five months',
      litter_size: '2',
      habitat:
        'Colder climates in the wild, but since they’ve been domesticated, anywhere',
      predators: 'Coyotes',
      diet: 'Herbivore',
      type: 'Ruminant',
      location: 'Asia, Australia, North America',
      color: 'BrownGreyBlackWhite',
      skin_type: 'Hair',
      top_speed: '10 mph',
      lifespan: 'Between 10 and 12 years',
      age_of_sexual_maturity:
        'Maturity Males reach sexual maturity between 4 and 8 months; females reach sexual maturity between 7 and 10 months',
      age_of_weaning: '4 months'
    }
  },
  {
    name: 'Goat',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Artiodactyla',
      family: 'Bovidae',
      genus: 'Capra'
    },
    locations: ['Africa', 'Asia', 'Eurasia', 'Europe'],
    characteristics: {
      main_prey: 'Grass, Fruit, Leaves',
      habitat: 'Dry woodland and mountainous regions',
      predators: 'Human, Wolf, Mountain Lion',
      diet: 'Herbivore',
      average_litter_size: '2',
      lifestyle: 'Herd',
      favorite_food: 'Grass',
      type: 'Mammal',
      slogan: 'Most closely related to the Sheep!',
      color: 'BrownBlackWhiteTan',
      skin_type: 'Fur',
      top_speed: '10 mph',
      lifespan: '10-15 years',
      weight: '54-77kg (120-170lbs)'
    }
  },
  {
    name: 'Kiko Goat',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Artiodactyla',
      family: 'Bovidae',
      genus: 'Capra',
      scientific_name: 'Capra aegagrus Hircus'
    },
    locations: ['North-America', 'Oceania'],
    characteristics: {
      name_of_young: 'kid',
      biggest_threat: 'Humans',
      gestation_period: '155 days',
      temperament: 'Friendly, docile, independent',
      litter_size: '2-3 kids (twins or triplets)',
      habitat: 'Farmland',
      predators: 'Coyotes, bears, bobcats, foxes, eagles, and mountain lions.',
      diet: 'Herbivore',
      lifestyle: 'Herd',
      favorite_food: 'Grass, hay, and other natural foliage around habitat.',
      common_name: 'Kiko goat',
      number_of_species: '1',
      location: 'New Zealand, southeastern United States',
      group: 'Herd',
      color: 'BrownBlackWhiteCream',
      skin_type: 'Fur',
      lifespan: '8-12 years',
      weight: '250-300 pounds',
      height: '26-37 inches',
      age_of_sexual_maturity: '12-18 months',
      age_of_weaning: '60-90 days'
    }
  },
  {
    name: 'Kinder Goat',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Artiodactyla',
      family: 'Bovidae',
      genus: 'Capra',
      scientific_name: 'Capra aegagrus hircus'
    },
    locations: ['North-America', 'South-America'],
    characteristics: {
      name_of_young: 'Kid',
      group_behavior: 'Herd',
      estimated_population_size: '3000',
      biggest_threat: 'Predators',
      most_distinctive_feature: 'Black stripe on back',
      gestation_period: '140 to 150 days',
      water_type: 'Saltwater',
      litter_size: '3 or more',
      habitat: 'Farms, pastures',
      diet: 'Herbivore',
      common_name: 'Kinder goat',
      number_of_species: '1',
      location: 'U.S., Canada and Brazil',
      group: 'Ungulate',
      color: 'BrownGreyBlackWhite',
      skin_type: 'Hair',
      lifespan: '15 years',
      weight: '115 to 150lbs',
      height: '2 to 3 feet',
      age_of_sexual_maturity: '4 to 10 months',
      age_of_weaning: '6 to 8 weeks'
    }
  },
  {
    name: 'LaMancha Goat',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Artiodactyla',
      family: 'Bovidae',
      genus: 'Capra',
      scientific_name: 'Capra aegagrus hircus'
    },
    locations: ['North-America'],
    characteristics: {
      name_of_young: 'Buckling, doeling, yearling',
      group_behavior: 'Herd',
      estimated_population_size: 'Unknown',
      biggest_threat: 'Predators',
      most_distinctive_feature: 'Tiny ears',
      other_names: 'American Lamancha',
      gestation_period: '150 days',
      litter_size: '1 to 3',
      habitat: 'Farms, pastures',
      predators: 'Wild dogs, cougars, wolves, raptors',
      diet: 'Herbivore',
      common_name: 'LaMancha Goat',
      number_of_species: '1',
      location: 'U.S.',
      group: 'Artiodactyl',
      color: 'BrownGreyBlackWhite',
      skin_type: 'Hair',
      lifespan: '7 to 10 years',
      weight: 'Average 150 to 165 for males, 125 to 130 for females',
      height: '2 to 3 feet',
      length: '3 to 3 ½ feet',
      age_of_sexual_maturity: '9 months to 1 year',
      age_of_weaning: '3 weeks'
    }
  },
  {
    name: 'Nigerian Goat',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Artiodactyla',
      family: 'Calvo',
      genus: 'Capra',
      scientific_name: 'Capra aegagrus hircus'
    },
    locations: ['Africa', 'North-America'],
    characteristics: {
      name_of_young: 'Kid',
      group_behavior: 'Herd',
      estimated_population_size: 'Unknown',
      biggest_threat: 'Predatory birds and mammals',
      most_distinctive_feature: 'Miniature size',
      gestation_period: '145-154 days',
      water_type: 'Saltwater',
      litter_size: '2-4',
      habitat: 'Farmland',
      diet: 'Herbivore',
      type: 'Caprid',
      common_name: 'Nigerian dwarf goat',
      location: 'United States',
      group: 'Herd',
      color: 'BrownRedBlackWhiteGoldCream',
      skin_type: 'Hair',
      lifespan: '15 years',
      weight: '40-70lbs',
      height: '16-22in',
      age_of_sexual_maturity: '3-8 months',
      age_of_weaning: '30-60 days'
    }
  },
  {
    name: 'Nubian Goat',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Artiodactyla',
      family: 'Bovidae',
      genus: 'Capra',
      scientific_name: 'Capra aegagrus hircus'
    },
    locations: ['North-America'],
    characteristics: {
      name_of_young: 'kid',
      group_behavior: 'Herd',
      estimated_population_size: '924 million',
      gestation_period: '150 days',
      litter_size: '2',
      diet: 'Herbivore',
      number_of_species: '1',
      color: 'BlackWhiteTanChestnut',
      skin_type: 'Hair',
      lifespan: '15 years in captivity, 12 years in the wild',
      weight: '135lbs',
      age_of_sexual_maturity: 'six months'
    }
  },
  {
    name: 'Pygora Goat',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Artiodactyla',
      family: 'Bovidae',
      genus: 'Capra',
      scientific_name: 'Capra aegagrus hircus'
    },
    locations: ['North-America'],
    characteristics: {
      name_of_young: 'Kid',
      group_behavior: 'Herd',
      estimated_population_size: 'unknown',
      biggest_threat: 'Poor care',
      most_distinctive_feature: 'Growth of three types of fleeces',
      other_names: 'Miniature Angora goat',
      gestation_period: '148-155 days',
      litter_size: '1-3',
      habitat: 'Farmland',
      predators: 'Dogs, coyotes, birds of prey, bobcats, foxes.',
      diet: 'Herbivore',
      type: 'Mammal',
      common_name: 'Pygora goat',
      number_of_species: '1',
      location: 'America',
      color: 'BrownGreyBlackWhite',
      skin_type: 'Fur',
      lifespan: '12-15 years',
      weight: '75-95 lbs. for males, 64-75 lbs. for females.',
      height: '23 inches for males, 18 inches for females',
      age_of_sexual_maturity: '4-6 months',
      age_of_weaning: '12 weeks'
    }
  },
  {
    name: 'Saanen Goat',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Artiodactyla',
      family: 'Bovidae',
      genus: 'Capra',
      scientific_name: 'Capra aegagrus hircus'
    },
    locations: ['Europe'],
    characteristics: {
      prey: 'grass and legume',
      name_of_young: 'kid or billy',
      estimated_population_size: '900,000',
      most_distinctive_feature: 'white skin and short white coat',
      other_names: 'Saanenziege, Chèvre de Gessenay, and Capra di Saanen',
      temperament: 'calm',
      habitat: 'cool weather and hilly terrain',
      predators: 'Coyotes, bobcats, wild dogs, and wolves',
      diet: 'Omnivore',
      average_litter_size: '2',
      lifestyle: 'HerdFlock',
      type: 'mammal',
      common_name: 'saanen goat',
      origin: 'Switzerland',
      number_of_species: '8',
      group: 'herd',
      color: 'WhiteCream',
      skin_type: 'Hair',
      lifespan: 'about 10 years',
      height: '30 inches',
      age_of_sexual_maturity: '9 months',
      age_of_weaning: '12 months'
    }
  },
  {
    name: 'Savanna Goat',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'artiodactyla',
      family: 'Bovidae',
      genus: 'Capra',
      scientific_name: 'Capra hircus'
    },
    locations: ['Africa', 'North-America', 'Oceania', 'South-America'],
    characteristics: {
      name_of_young: 'Kid',
      group_behavior: 'Flock',
      estimated_population_size: '3,000 in the U.S., South Africa unknown',
      most_distinctive_feature: 'Solid white coat with black skin',
      gestation_period: '150 days',
      litter_size: '1-3 kids',
      habitat: 'savanna mixed woodland-grassland',
      predators:
        'humans, foxes, wolves, coyotes, mountain lions, bobcats, bears, eagles, dogs',
      diet: 'Herbivore',
      type: 'Mammal',
      common_name: 'savanna goat',
      number_of_species: '-1',
      location:
        'South Africa, South America, United States, New Zealand, Australia',
      color: 'BlackWhite',
      skin_type: 'Hair',
      lifespan: '15-18 years',
      weight: '132 pounds',
      height: '1.64ft - 2.08ft',
      age_of_sexual_maturity: '4-6 months',
      age_of_weaning: '10 to 12 weeks'
    }
  },
  {
    name: 'Spanish Goat',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Artiodactyla',
      family: 'Calvo',
      genus: 'Capra',
      scientific_name: 'Capra aegagrus hircus'
    },
    locations: ['Central-America', 'Europe', 'North-America'],
    characteristics: {
      prey: 'Grass, herbs, shrubs, weeds, tree barks, and leaves',
      name_of_young: 'Calf',
      group_behavior: 'Herd',
      estimated_population_size: 'approximately 500,000',
      biggest_threat: 'Domesticated dogs, wolves, foxes, and coyotes',
      most_distinctive_feature:
        'Long horizontal ears and thorns that are twisted at the points.',
      other_names: 'Brush goats and scrub goats',
      gestation_period: 'About 155 days',
      litter_size: '2-4',
      habitat: 'Spain, Mexico, and the USA',
      predators: 'Domesticated dogs, wolves, foxes, and coyotes',
      diet: 'Herbivore',
      color: 'BrownGreyFawn',
      lifespan: '6-7 years',
      weight: 'male: 200 to 250 lbs. females: 11 to 150 lbs.',
      height: '20 inches',
      length: '20 inches',
      age_of_sexual_maturity: '5 months to 1 year'
    }
  },
  {
    name: 'Red Panda',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Carnivora',
      family: 'Ailuridae',
      genus: 'Ailurus',
      scientific_name: 'Ailurus fulgens'
    },
    locations: ['Asia'],
    characteristics: {
      prey: 'Bamboo, Berries, Eggs',
      name_of_young: 'Cub',
      group_behavior: 'Solitary',
      estimated_population_size: 'less than 3,000',
      biggest_threat: 'Habitat loss',
      most_distinctive_feature: 'Rusty coloured thick fur and striped face',
      other_names: 'Lesser Panda, Fire Fox',
      gestation_period: '4 months',
      habitat: 'High-altitude mountain forest',
      predators: 'Snow Leopard, Marten, Human',
      diet: 'Omnivore',
      average_litter_size: '3',
      lifestyle: 'Nocturnal',
      common_name: 'Red Panda',
      number_of_species: '1',
      location: 'Himalayas',
      slogan: 'There are less than 3,000 left in the wild!',
      group: 'Mammal',
      color: 'BrownRedWhite',
      skin_type: 'Fur',
      top_speed: '24 mph',
      lifespan: '8 - 12 years',
      weight: '3kg - 6.2kg (7lbs - 14lbs)',
      length: '60cm - 120cm (24in - 47in)',
      age_of_sexual_maturity: '18 months',
      age_of_weaning: '5 months'
    }
  },
  {
    name: 'Polar Bear',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Carnivora',
      family: 'Ursidae',
      genus: 'Ursus',
      scientific_name: 'Ursus maritimus'
    },
    locations: ['Eurasia', 'Europe', 'North-America', 'Ocean'],
    characteristics: {
      prey: 'Seal, Walrus, Seabirds',
      name_of_young: 'Cub',
      group_behavior: 'Solitary',
      estimated_population_size: '20,000 - 25,000',
      biggest_threat: 'Global warming',
      most_distinctive_feature: 'Clear not white fur and black skin',
      other_names: 'Nanuuq',
      gestation_period: '6 - 9 months',
      habitat: 'Coastal ice fields and floating ice',
      diet: 'Carnivore',
      average_litter_size: '2',
      lifestyle: 'Diurnal',
      common_name: 'Polar Bear',
      number_of_species: '1',
      location: 'Arctic Ocean',
      slogan: 'Could be extinct within the next 30 years!',
      group: 'Mammal',
      color: 'YellowWhite',
      skin_type: 'Fur',
      top_speed: '25 mph',
      lifespan: '20 - 30 years',
      weight: '150kg - 600kg (330lbs - 1,322lbs)',
      length: '2m - 2.5m (6.5ft - 8.3ft)',
      age_of_sexual_maturity: '3 - 5 years',
      age_of_weaning: '2 - 3 years'
    }
  },
  {
    name: 'Cape Lion',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Carnivora',
      family: 'Felidae',
      genus: 'Panthera',
      scientific_name: 'Panthera leo melanochaitus'
    },
    locations: ['Africa'],
    characteristics: {
      prey: 'Wildebeests, antelopes, zebras, buffalos, rodents, and more',
      name_of_young: 'cub',
      group_behavior: 'Pride',
      biggest_threat: 'Habitat loss and hunting',
      most_distinctive_feature: 'The male’s dark-colored mane',
      gestation_period: 'around 100 days',
      litter_size: '1-6 cubs',
      habitat: 'plains',
      diet: 'Carnivore',
      type: 'mammal',
      common_name: 'Cape Lion',
      origin: 'South Africa',
      number_of_species: '1',
      location: 'South Africa',
      color: 'BrownYellowWhiteOrange',
      skin_type: 'Hair',
      top_speed: '48 mph',
      lifespan: '25 years',
      weight: 'up to 600 pounds',
      height: '4 feet',
      length: '6-7 feet',
      age_of_sexual_maturity: '3-4 years',
      age_of_weaning: '6-7 months'
    }
  },
  {
    name: 'Golden Lion Tamarin',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Primates',
      family: 'Callitrichidae',
      genus: 'Leontopithecus',
      scientific_name: 'Leontopithecus rosalia'
    },
    locations: ['South-America'],
    characteristics: {
      main_prey: 'Fruit, Insects, Small Mammals, Small Reptiles',
      habitat: 'Lowland tropical forest',
      predators: 'Hawks, Wild Cats, Snakes, Rats',
      diet: 'Omnivore',
      average_litter_size: '2',
      lifestyle: 'Troop',
      favorite_food: 'Fruit',
      type: 'Mammal',
      slogan: 'Native to the eastern rainforests of Brazil!',
      color: 'BrownBlackGoldOrange',
      skin_type: 'Hair',
      top_speed: '24 mph',
      lifespan: '8-15 years',
      weight: '550-700g (19-25oz)'
    }
  },
  {
    name: 'Lion',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Carnivora',
      family: 'Felidae',
      genus: 'Panthera',
      scientific_name: 'Panthera leo'
    },
    locations: ['Africa', 'Asia'],
    characteristics: {
      prey: 'Antelope, Warthog, Zebra',
      name_of_young: 'Cub',
      group_behavior: 'Pride',
      estimated_population_size: '23,000',
      biggest_threat: 'Habitat loss',
      most_distinctive_feature:
        'Long and thick hairy mane of the male around the face',
      other_names: 'African Lion',
      gestation_period: '110 days',
      habitat: 'open woodland, scrub, grassland',
      diet: 'Carnivore',
      average_litter_size: '3',
      lifestyle: 'Diurnal/Nocturnal',
      common_name: 'Lion',
      number_of_species: '2',
      location: 'sub-Saharan Africa',
      slogan: 'Lives in small groups called prides!',
      group: 'Mammal',
      color: 'BrownGoldTawnyBlonde',
      skin_type: 'Fur',
      top_speed: '35 mph',
      lifespan: '8 - 15 years',
      weight: '120kg - 249kg (264lbs - 550lbs)',
      length: '1.4m - 2.5m (4.7ft - 8.2ft)',
      age_of_sexual_maturity: '2 - 3 years',
      age_of_weaning: '6 months'
    }
  },
  {
    name: 'Lion’s Mane Jellyfish',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Cnidaria',
      class: 'Scyphozoa',
      order: 'Semaeostomeae',
      family: 'Cyaneidae',
      genus: 'Cyanea',
      scientific_name: 'Cyanea capillata'
    },
    locations: ['Ocean'],
    characteristics: {
      prey: 'Fish, zooplankton, shrimp, other jellyfish',
      group_behavior: 'Solitary/School',
      estimated_population_size:
        'Possibly millions its IUCN conservation status is unevaluated, but not in danger of extinction',
      biggest_threat: 'Pollution',
      most_distinctive_feature: 'Its size',
      other_names:
        'Giant jellyfish, hair jellyfish, hair jellyfish, mane jellyfish, Arctic red jellyfish, sea nettle, sea blubber, winter jellyfish',
      gestation_period: 'One day',
      water_type: 'Salt',
      optimum_ph_level: '8.1',
      habitat: 'Cooler ocean waters',
      predators:
        'Seabirds, sea turtles, anemones, ocean sunfish, larger jellies but only when the jellyfish is a juvenile.',
      diet: 'Carnivore',
      type: 'Cnidarian',
      common_name: 'Lion’s Mane Jellyfish',
      number_of_species: '1',
      color: 'YellowRedWhiteOrangePurple',
      lifespan: 'One year',
      weight: '200 pounds',
      length: 'As much as 120 feet'
    }
  },
  {
    name: 'Lionfish',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Actinopterygii',
      order: 'Scorpaeniformes',
      family: 'Scorpaenidae',
      genus: 'Pterois',
      scientific_name: 'Pterois volitans'
    },
    locations: ['Ocean'],
    characteristics: {
      main_prey: 'Fish, Shrimp, Crabs',
      distinctive_feature: 'Striped body markings with long spines',
      water_type: 'Salt',
      optimum_ph_level: '8.1 - 8.4',
      habitat: 'Tropical reefs and rocky crevices',
      predators: 'Eels, Frogfish, Scorpion Fish',
      diet: 'Carnivore',
      favorite_food: 'Fish',
      common_name: 'Lionfish',
      average_clutch_size: '8000',
      slogan: 'Females can release up to 15,000 eggs at a time!',
      color: 'BrownRedBlackWhiteOrange',
      skin_type: 'Scales',
      lifespan: '10 - 18 years',
      length: '30cm - 35cm (12in - 14in)'
    }
  },
  {
    name: 'Mountain Lion',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Carnivora',
      family: 'Felidae',
      genus: 'Puma',
      scientific_name: 'Felis Concolor'
    },
    locations: ['Central-America', 'North-America', 'South-America'],
    characteristics: {
      main_prey: 'Deer, Elk, Beavers',
      litter_size: '3',
      habitat: 'Forest and mountainous regions',
      predators: 'Human, Grizzly Bear',
      diet: 'Carnivore',
      lifestyle: 'Solitary',
      favorite_food: 'Deer',
      type: 'Mammal',
      origin: '3',
      slogan: 'Has no real natural predators!',
      color: 'BrownBlackTan',
      skin_type: 'Fur',
      top_speed: '30 mph',
      lifespan: '10-20 years',
      weight: '29-90kg (64-198lbs)'
    }
  },
  {
    name: 'Sea Lion',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Carnivora',
      family: 'Otariidae',
      scientific_name: 'Otariidae'
    },
    locations: ['Ocean'],
    characteristics: {
      main_prey: 'Fish, Crabs, Squid',
      habitat: 'Coastal waters and rocky shorelines',
      predators: 'Human, Sharks, Killer Whale',
      diet: 'Omnivore',
      average_litter_size: '1',
      lifestyle: 'Herd',
      favorite_food: 'Fish',
      type: 'Mammal',
      slogan: "It's flippers allow it to walk on the land",
      color: 'BrownGreyTan',
      skin_type: 'Fur',
      top_speed: '27 mph',
      lifespan: '15-22 years',
      weight: '300-1,000kg (660-2,200lbs)'
    }
  },
  {
    name: 'Bengal Tiger',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Carnivora',
      family: 'Felidae',
      genus: 'Panthera',
      scientific_name: 'Panthera Tigris Tigris'
    },
    locations: ['Asia'],
    characteristics: {
      main_prey: 'Deer, Cattle, Wild Boar',
      habitat: 'Dense tropical forest and mangroves',
      predators: 'Human',
      diet: 'Carnivore',
      average_litter_size: '3',
      lifestyle: 'Solitary',
      favorite_food: 'Deer',
      type: 'Mammal',
      slogan: 'The most numerous species of tiger!',
      color: 'BlackWhiteOrange',
      skin_type: 'Fur',
      top_speed: '60 mph',
      lifespan: '18 - 25 years',
      weight: '140kg - 300kg (309lbs - 660lbs)',
      length: '2.4m - 3.3m (6.8ft - 11ft)'
    }
  },
  {
    name: 'Indochinese Tiger',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Carnivora',
      family: 'Felidae',
      genus: 'Panthera',
      scientific_name: 'Panthera Tigris Corbetti'
    },
    locations: ['Asia'],
    characteristics: {
      main_prey: 'Deer, Cattle, Wild Boar',
      habitat: 'Secluded mountainous forests',
      predators: 'Human',
      diet: 'Carnivore',
      average_litter_size: '2',
      lifestyle: 'Solitary',
      favorite_food: 'Deer',
      type: 'Mammal',
      slogan: 'Now thought to be extinct in China!',
      color: 'BlackWhiteOrange',
      skin_type: 'Fur',
      top_speed: '60 mph',
      lifespan: '18 - 25 years',
      weight: '100kg - 195kg (221lbs - 430lbs)'
    }
  },
  {
    name: 'Malayan Tiger',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Carnivora',
      family: 'Felidae',
      genus: 'Panthera',
      scientific_name: 'Panthera Tigris Jacksoni'
    },
    locations: ['Asia'],
    characteristics: {
      main_prey: 'Deer, Cattle, Wild Boar',
      habitat: 'Dense tropical forest',
      predators: 'Human',
      diet: 'Carnivore',
      average_litter_size: '3',
      lifestyle: 'Solitary',
      favorite_food: 'Deer',
      type: 'Mammal',
      slogan: 'Found in less-dense jungles!',
      color: 'BlackWhiteOrange',
      skin_type: 'Fur',
      top_speed: '60 mph',
      lifespan: '18 - 25 years',
      weight: '80kg - 150kg (176lbs - 330lbs)'
    }
  },
  {
    name: 'Saber-Toothed Tiger',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Carnivora',
      family: 'Felidae',
      genus: 'Smilodon',
      scientific_name: 'Smilodon populator'
    },
    locations: ['Central-America', 'North-America', 'South-America'],
    characteristics: {
      main_prey: 'Deer, Bison, Woolly Mammoth',
      distinctive_feature: 'Large muscular body and long canine teeth',
      habitat: 'Forests and grasslands',
      predators: 'Humans',
      diet: 'Carnivore',
      average_litter_size: '3',
      lifestyle: 'Pack',
      favorite_food: 'Deer',
      type: 'Mammal',
      slogan: 'Canines up to 7 inches long!',
      color: 'BrownYellowBlackWhiteTan',
      skin_type: 'Fur',
      lifespan: '20 - 40 years',
      weight: '300kg (661lbs)',
      length: '2m - 2.5m (79in - 98in)'
    }
  },
  {
    name: 'Sand Tiger Shark',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Chondrichthyes',
      order: 'Lamniformes',
      family: 'Odontaspididae'
    },
    locations: ['Ocean'],
    characteristics: {
      prey: 'Bony fish, other sharks, crustaceans, squid, skates and rays',
      group_behavior: 'Solitary/Group',
      estimated_population_size:
        'Unknown, but its population decreased by 20 percent in just the last decade due to overfishing.',
      biggest_threat: 'Humans',
      most_distinctive_feature: 'It gulps air to keep buoyant.',
      other_names:
        'spotted ragged-tooth shark, blue-nurse sand tiger, grey nurse shark, spotted sand tiger shark, chien de mer, dogfish shark, slender-tooth shark, magonga, requin taureau, ground shark',
      gestation_period: 'Eight to twelve months',
      habitat: 'Shallow tropical and temperate waters close to the shore',
      diet: 'Carnivore',
      type: 'Fish',
      common_name: 'Sand tiger shark',
      number_of_species: '4',
      color: 'Grey-Brown',
      skin_type: 'Rough',
      top_speed: '0.87 mph',
      lifespan: '13 to 35 years',
      weight: '110 to 660.79 pounds',
      length: '6.6 to 10.5 feet'
    }
  },
  {
    name: 'Siberian Tiger',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Carnivora',
      family: 'Felidae',
      genus: 'Panthera',
      scientific_name: 'Panthera Tigris Altaica'
    },
    locations: ['Asia', 'Eurasia'],
    characteristics: {
      main_prey: 'Deer, Cattle, Wild Boar',
      habitat: 'Dense tropical forest',
      predators: 'Human',
      diet: 'Carnivore',
      average_litter_size: '3',
      lifestyle: 'Solitary',
      favorite_food: 'Deer',
      type: 'Mammal',
      slogan: 'Also known as the Amur tiger!',
      color: 'BlackWhiteOrange',
      skin_type: 'Fur',
      top_speed: '60 mph',
      lifespan: '18 - 25 years',
      weight: '100kg - 350kg (220lbs - 770lbs)'
    }
  },
  {
    name: 'South China Tiger',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Carnivora',
      family: 'Felidae',
      genus: 'Panthera',
      scientific_name: 'Panthera Tigris Amoyensis'
    },
    locations: ['Asia'],
    characteristics: {
      main_prey: 'Deer, Cattle, Wild Boar',
      habitat: 'Dense tropical forest',
      predators: 'Human',
      diet: 'Carnivore',
      average_litter_size: '3',
      lifestyle: 'Solitary',
      favorite_food: 'Deer',
      type: 'Mammal',
      slogan: 'There are less than 20 in the wild!',
      color: 'BlackWhiteOrange',
      skin_type: 'Fur',
      top_speed: '60 mph',
      lifespan: '18 - 25 years',
      weight: '100kg - 195kg (221lbs - 430lbs)'
    }
  },
  {
    name: 'Sumatran Tiger',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Carnivora',
      family: 'Felidae',
      genus: 'Panthera',
      scientific_name: 'Panthera Tigris Sumatrae'
    },
    locations: ['Asia'],
    characteristics: {
      main_prey: 'Deer, Cattle, Wild Boar',
      habitat: 'Dense tropical forest',
      predators: 'Human',
      diet: 'Carnivore',
      average_litter_size: '3',
      lifestyle: 'Solitary',
      favorite_food: 'Deer',
      type: 'Mammal',
      slogan: 'The smallest species of tiger!',
      color: 'BlackWhiteOrange',
      skin_type: 'Fur',
      top_speed: '60 mph',
      lifespan: '18 - 25 years',
      weight: '80kg - 150kg (176lbs - 330lbs)'
    }
  },
  {
    name: 'Tasmanian Tiger',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Dasyuromorphia',
      family: '†Thylacinidae',
      genus: '†Thylacinus',
      scientific_name: '†Thylacinus cynocephalus'
    },
    locations: ['Oceania'],
    characteristics: {
      prey: 'Birds, kangaroos, wombats, emus, possums, wallabies. echidnas, bettongs, bandicoots, potoroos and small livestock',
      name_of_young: 'Joey',
      group_behavior: 'Solitary',
      estimated_population_size: 'Possibly extinct',
      biggest_threat: 'Humans',
      most_distinctive_feature: 'Marsupial pouch',
      other_names:
        'Tasmanian wolf, thylacine, kaparunina, loarinna, laoonana, coorinna, kanunnah, cab-berr-one-nen-er, lagunta, can-nen-ner',
      gestation_period: 'Two weeks, possibly',
      litter_size: 'Two to four joeys',
      habitat: 'Grasslands and forests, rainforests',
      predators: 'None, save humans and dingos',
      diet: 'Carnivore',
      type: 'Marsupial',
      common_name: 'Tasmanian tiger',
      number_of_species: '1',
      location: 'Tasmania',
      group: 'Solitary',
      color: 'TanDark Brown',
      skin_type: 'Fur',
      lifespan: 'Eight to 10 years',
      weight: '18 to 66 pounds',
      height: '24 inches at the shoulder',
      length: '39 to 51 inches plus 20 to 26-inch tail',
      age_of_sexual_maturity: 'Unknown',
      age_of_weaning: 'Two months'
    }
  },
  {
    name: 'Tiger',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Carnivora',
      family: 'Felidae',
      genus: 'Panthera',
      scientific_name: 'Panthera Tigris'
    },
    locations: ['Asia', 'Eurasia'],
    characteristics: {
      main_prey: 'Deer, Cattle, Wild Boar',
      habitat: 'Dense tropical forest',
      predators: 'Human',
      diet: 'Carnivore',
      average_litter_size: '3',
      lifestyle: 'Solitary',
      favorite_food: 'Deer',
      type: 'Mammal',
      slogan: 'The largest feline in the world!',
      color: 'BlackWhiteOrange',
      skin_type: 'Fur',
      top_speed: '60 mph',
      lifespan: '18-25 years',
      weight: '267-300kg (589-660lbs)'
    }
  },
  {
    name: 'Tiger Beetle',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Arthropoda',
      class: 'Insecta',
      order: 'Coleoptera',
      family: 'Carabidae',
      genus: 'Cicindela',
      scientific_name: 'Cicindelinae'
    },
    locations: [
      'Africa',
      'Antarctica',
      'Asia',
      'Central-America',
      'Eurasia',
      'Europe',
      'North-America',
      'Oceania',
      'South-America'
    ],
    characteristics: {
      prey: 'spiders and insects',
      name_of_young: 'larvae',
      group_behavior: 'Solitary',
      biggest_threat: 'Habitat destruction',
      most_distinctive_feature: 'The iridescent metallic shell',
      gestation_period: 'a few days or weeks',
      litter_size: '3-4 eggs per day',
      habitat: 'ground',
      diet: 'Carnivore',
      type: 'insect',
      common_name: 'Tiger beetle',
      number_of_species: '2600',
      location: 'worldwide',
      color: 'RedBlueBlackWhiteGreenOrange',
      skin_type: 'Exoskeleton',
      top_speed: '3.5 mph',
      lifespan: '1-4 years',
      weight: 'less than 1 gram',
      length: 'up to 1 inch',
      age_of_sexual_maturity: '1-4 years'
    }
  },
  {
    name: 'Tiger Moth',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Arthropoda',
      class: 'Insecta',
      order: 'Lepidoptera',
      family: 'Erebidae',
      genus: 'Arctia'
    },
    locations: ['Asia', 'Eurasia', 'Europe', 'North-America'],
    characteristics: {
      name_of_young: 'Caterpillar, larva',
      group_behavior: 'Solitary',
      biggest_threat: 'Habitat loss',
      most_distinctive_feature: 'Brightly colored pattern on its wings',
      other_names: 'Woolly bear (caterpillars)',
      gestation_period: ' Eggs hatch in 10 days',
      wingspan: '1.5-2 inches',
      litter_size: '50 or more',
      habitat: 'Grasslands, forests',
      predators: 'Some birds',
      diet: 'Herbivore',
      favorite_food: 'plants, nectar',
      type: 'Insect',
      common_name: 'tiger moth',
      number_of_species: '11000',
      location: 'North America, Europe, Central Asia, Northern Asia',
      color: 'RedBlackWhiteGreenOrange',
      skin_type: 'Hair',
      lifespan: '5-10 days',
      weight: 'less than 1 ounce'
    }
  },
  {
    name: 'Tiger Rattlesnake',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Reptilia',
      order: 'Squamata',
      family: 'Viperidae',
      genus: 'Crotalus',
      scientific_name: 'C. tigris'
    },
    locations: ['Central-America', 'North-America'],
    characteristics: {
      prey: 'Small mammals and lizards',
      main_prey: 'Adults - mainly small mammals; juveniles - mainly lizards',
      name_of_young: 'Neonate',
      group_behavior: 'SolitarySolitary except during mating season',
      estimated_population_size: '10,000',
      biggest_threat: 'Human expansion',
      most_distinctive_feature: 'Small head and large rattle',
      distinctive_feature:
        '"Tiger stripes" in the form of crossbands down the length of the snake',
      other_names: 'Tiger rattler',
      diet: 'Carnivore',
      average_litter_size: '6-10',
      lifestyle: 'NocturnalCrepuscular',
      common_name: 'Tiger Rattlesnake',
      location: 'Central Arizona south to northern Mexico',
      color: 'BrownYellowFawnTanOrangeLilac',
      skin_type: 'Scales',
      length: '2-3 feet',
      venomous: 'Yes',
      aggression: 'Low'
    }
  },
  {
    name: 'Tiger Salamander',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Amphibia',
      order: 'Caudata',
      family: 'Ambystomatidae',
      genus: 'Ambystoma',
      scientific_name: 'Ambystoma tigrinum'
    },
    locations: ['North-America', 'Ocean'],
    characteristics: {
      main_prey: 'Insects, Worms, Small Frogs',
      habitat: 'Wetlands, rivers and streams',
      predators: 'Raccoon, Coati, River Turtles',
      diet: 'Carnivore',
      lifestyle: 'Solitary',
      favorite_food: 'Insects',
      type: 'Amphibian',
      average_clutch_size: '50',
      slogan: 'Found across the North American wetlands!',
      color: 'BrownGreyYellowBlackGreen',
      skin_type: 'Permeable',
      top_speed: '10 mph',
      lifespan: '10-15 years',
      weight: '113-227g (4-8oz)'
    }
  },
  {
    name: 'Tiger Shark',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Chondrichthyes',
      order: 'Carcharhiniformes',
      family: 'Carcharhinidae',
      genus: 'Galeocerdo',
      scientific_name: 'Galeocerdo Cuvier'
    },
    locations: ['Ocean'],
    characteristics: {
      main_prey: 'Squid, Fish, Turtles',
      habitat: 'Tropical coastal waters',
      predators: 'Human',
      diet: 'Carnivore',
      average_litter_size: '35',
      lifestyle: 'Solitary',
      favorite_food: 'Squid',
      type: 'Fish',
      slogan: 'The fourth biggest species of shark in the world!',
      color: 'BrownGreyBlackWhite',
      skin_type: 'Smooth',
      top_speed: '20 mph',
      lifespan: '30-40 years',
      weight: '385-635kg (850-1,400lbs)'
    }
  },
  {
    name: 'White Tiger',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Carnivora',
      family: 'Felidae',
      genus: 'Panthera',
      scientific_name: 'Panthera tigris tigris'
    },
    locations: ['Asia', 'Eurasia'],
    characteristics: {
      prey: 'Deer, Cattle, Wild Boar',
      name_of_young: 'Cub',
      group_behavior: 'Solitary',
      estimated_population_size: '0 in wild',
      biggest_threat: 'Habitat loss',
      most_distinctive_feature: 'White fur with bright, blue eyes',
      other_names: 'White Bengal Tiger',
      gestation_period: '103 days',
      habitat: 'Dense jungle and mangrove swamp',
      predators: 'Human',
      diet: 'Carnivore',
      average_litter_size: '3',
      lifestyle: 'Diurnal',
      common_name: 'White Tiger',
      number_of_species: '1',
      location: 'Indian subcontinent',
      slogan: 'None have been seen in the wild for 50 years!',
      group: 'Mammal',
      color: 'BrownBlackWhiteOrange',
      skin_type: 'Fur',
      top_speed: '60 mph',
      lifespan: '10 - 20 years',
      weight: '140kg - 300kg (309lbs - 660lbs)',
      length: '2.4m - 3.3m (6.8ft - 11ft)',
      age_of_sexual_maturity: '3 - 4 years',
      age_of_weaning: '6 months'
    }
  },
  {
    name: 'African Bush Elephant',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Proboscidea',
      family: 'Elephantidae',
      genus: 'Loxodonta',
      scientific_name: 'Loxodonta africana africana'
    },
    locations: ['Africa'],
    characteristics: {
      prey: 'Grass, Fruit, Roots',
      name_of_young: 'Calf',
      group_behavior: 'Herd',
      estimated_population_size: '300,000',
      biggest_threat: 'Poaching and habitat loss',
      most_distinctive_feature: 'Large, rounded ears',
      other_names: 'African Elephant',
      gestation_period: '20 - 24 months',
      habitat: 'Forest, savannah and flood plains',
      predators: 'Human, Lion, Hyena',
      diet: 'Herbivore',
      average_litter_size: '1',
      lifestyle: 'Diurnal',
      common_name: 'African Bush Elephant',
      number_of_species: '1',
      location: 'central and southern Africa',
      slogan: 'Can drink up to 50 gallons a day',
      group: 'Mammal',
      color: 'BrownGrey',
      skin_type: 'Leather',
      top_speed: '25 mph',
      lifespan: '60 - 70 years',
      weight: '3,600kg - 5,400kg (7,900lbs - 12,000lbs)',
      height: '3m - 3.5m (10ft - 12ft)',
      age_of_sexual_maturity: '11 - 20 years',
      age_of_weaning: '6 - 18 months'
    }
  },
  {
    name: 'African Forest Elephant',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Proboscidea',
      family: 'Elephantidae',
      genus: 'Loxodonta',
      scientific_name: 'Loxodonta cyclotis'
    },
    locations: ['Africa'],
    characteristics: {
      prey: 'Grass, Fruit, Roots',
      name_of_young: 'Calf',
      group_behavior: 'Herd',
      estimated_population_size: '200,000',
      biggest_threat: 'Poaching and habitat loss',
      most_distinctive_feature: 'Rounded ears and thin, straight tusks',
      other_names: 'African Elephant',
      gestation_period: '22 - 24 months',
      habitat: 'Forest, savannah and flood plains',
      predators: 'Human, Lion, Hyena',
      diet: 'Herbivore',
      average_litter_size: '1',
      lifestyle: 'Diurnal',
      common_name: 'African Forest Elephant',
      number_of_species: '1',
      location: 'central and southern Africa',
      slogan: 'Have large rounded ears to help keep them cool!',
      group: 'Mammal',
      color: 'BrownGrey',
      skin_type: 'Leather',
      top_speed: '24 mph',
      lifespan: '60 - 70 years',
      weight: '900kg - 3,000kg (1,984lbs - 6,613lbs)',
      height: '2m - 3m (6.6ft - 9.8ft)',
      age_of_sexual_maturity: '11 - 20 years',
      age_of_weaning: '5 years'
    }
  },
  {
    name: 'Asian Elephant',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Proboscidea',
      family: 'Elephantidae',
      genus: 'Elephas',
      scientific_name: 'Elephas maximus'
    },
    locations: ['Asia'],
    characteristics: {
      main_prey: 'Grass, Fruit, Roots',
      distinctive_feature: 'Long trunk and large feet',
      habitat: 'Rainforest and tropical woodland',
      predators: 'Human, Tiger',
      diet: 'Herbivore',
      average_litter_size: '1',
      lifestyle: 'Herd',
      favorite_food: 'Grass',
      type: 'Mammal',
      slogan: 'Domesticated for hundreds of years!',
      color: 'BrownGreyBlack',
      skin_type: 'Leather',
      top_speed: '27 mph',
      lifespan: '55 - 70 years',
      weight: '3,000kg - 5,000kg (6,500lbs - 11,000lbs)',
      height: '2m - 3m (7ft - 10ft)'
    }
  },
  {
    name: 'Borneo Elephant',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Proboscidea',
      family: 'Elephantidae',
      genus: 'Elephas',
      scientific_name: 'Elephas maximus borneensis'
    },
    locations: ['Asia', 'Ocean'],
    characteristics: {
      main_prey: 'Grass, Fruit, Roots',
      distinctive_feature: 'Long trunk and large feet',
      habitat: 'Rainforest and tropical woodland',
      predators: 'Human, Tiger',
      diet: 'Herbivore',
      average_litter_size: '1',
      lifestyle: 'Herd',
      favorite_food: 'Grass',
      type: 'Mammal',
      slogan: 'The smallest species of elephant!',
      color: 'BrownGreyBlack',
      skin_type: 'Leather',
      top_speed: '27 mph',
      lifespan: '55 - 70 years',
      weight: '3,000kg - 5,000kg (6,500lbs - 11,000lbs)',
      height: '2m - 3m (7ft - 10ft)'
    }
  },
  {
    name: 'Elephant',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Proboscidea',
      family: 'Elephantidae'
    },
    locations: ['Africa', 'Asia'],
    characteristics: {
      main_prey: 'Grass, Fruit, Roots',
      distinctive_feature: 'Large body size and long trunk',
      habitat: 'Rainforest and flood plains',
      diet: 'Herbivore',
      average_litter_size: '1',
      lifestyle: 'Herd',
      favorite_food: 'Grass',
      type: 'Mammal',
      slogan: 'Spends around 22 hours a day eating!',
      color: 'Grey',
      skin_type: 'Leather',
      top_speed: '25 mph',
      lifespan: '55 - 70 years',
      weight: '3,000kg - 5,400kg (6,500lbs - 12,000lbs)',
      height: '2m - 3.6m (7ft - 12ft)'
    }
  },
  {
    name: 'Elephant Seal',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Carnivora',
      family: 'Phocidae',
      genus: 'Mirounga',
      scientific_name: 'Mirounga'
    },
    locations: ['Ocean'],
    characteristics: {
      main_prey: 'Fish, Squid, Octopus',
      distinctive_feature: 'Long trunk-like nose and large body',
      habitat: 'Warm coastal waters close to land',
      predators: 'Human, Sharks, Killer Whales',
      diet: 'Carnivore',
      average_litter_size: '1',
      lifestyle: 'Herd',
      favorite_food: 'Fish',
      type: 'Mammal',
      slogan: 'The largest species of seal in the world!',
      color: 'BrownGreyBlackTan',
      skin_type: 'Fur',
      top_speed: '12 mph',
      lifespan: '18 - 22 years',
      weight: '900kg - 3,000kg (2,000lbs - 6,000lbs)',
      length: '3m - 5m (10ft - 16ft)'
    }
  },
  {
    name: 'Elephant Shrew',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Macroscelidea',
      family: 'Macroscelididae',
      genus: 'Elephantulus',
      scientific_name: 'Elephantulus'
    },
    locations: ['Africa'],
    characteristics: {
      main_prey: 'Insects, Worms, Spiders',
      distinctive_feature: 'Long nose and long back legs',
      habitat: 'Forest, woodland and grassland',
      predators: 'Snakes, Lizards, Birds of Prey',
      diet: 'Omnivore',
      average_litter_size: '2',
      lifestyle: 'Solitary',
      favorite_food: 'Insects',
      type: 'Mammal',
      slogan: 'Found exclusively on the African continent!',
      color: 'BrownGreyBlackWhiteTan',
      skin_type: 'Fur',
      top_speed: '8 mph',
      lifespan: '2 - 5 years',
      weight: '50g - 500g (2oz - 18oz)',
      length: '10cm - 30cm (4in - 12in)'
    }
  },
  {
    name: 'Indian Elephant',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Proboscidea',
      family: 'Elephantidae',
      genus: 'Elephas',
      scientific_name: 'Elephas maximus indicus'
    },
    locations: ['Asia'],
    characteristics: {
      main_prey: 'Grass, Fruit, Roots',
      distinctive_feature: 'Long trunk and large feet',
      habitat: 'Rainforest and tropical woodland',
      predators: 'Human, Tiger',
      diet: 'Herbivore',
      average_litter_size: '1',
      lifestyle: 'Herd',
      favorite_food: 'Grass',
      type: 'Mammal',
      slogan: 'Found throughout south-east Asia!',
      color: 'BrownGreyBlack',
      skin_type: 'Leather',
      top_speed: '27 mph',
      lifespan: '55 - 70 years',
      weight: '3,000kg - 5,000kg (6,500lbs - 11,000lbs)',
      height: '2m - 3m (7ft - 10ft)'
    }
  },
  {
    name: 'Sri Lankan Elephant',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Proboscidea',
      family: 'Elephantidae',
      genus: 'Elephas',
      scientific_name: 'Elephas Maximus Maximus'
    },
    locations: ['Asia'],
    characteristics: {
      main_prey: 'Grass, Fruit, Roots',
      distinctive_feature: 'Long trunk and large feet',
      habitat: 'Rainforest and tropical woodland',
      predators: 'Human, Tiger',
      diet: 'Herbivore',
      average_litter_size: '1',
      lifestyle: 'Herd',
      favorite_food: 'Grass',
      type: 'Mammal',
      slogan: 'Now restricted to a few parks!',
      color: 'BrownGreyBlack',
      skin_type: 'Leather',
      top_speed: '27 mph',
      lifespan: '55 - 70 years',
      weight: '3,000kg - 5,000kg (6,500lbs - 11,000lbs)',
      height: '2m - 3m (7ft - 10ft)'
    }
  },
  {
    name: 'Sumatran Elephant',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Proboscidea',
      family: 'Elephantidae',
      genus: 'Elephas',
      scientific_name: 'Elephas Maximus Sumatranus'
    },
    locations: ['Asia'],
    characteristics: {
      main_prey: 'Grass, Fruit, Roots',
      distinctive_feature: 'Long trunk and large feet',
      habitat: 'Rainforest and tropical woodland',
      predators: 'Human, Tiger',
      diet: 'Herbivore',
      average_litter_size: '1',
      lifestyle: 'Herd',
      favorite_food: 'Grass',
      type: 'Mammal',
      slogan: 'Less than 2,000 left in the wild!',
      color: 'BrownGreyBlack',
      skin_type: 'Leather',
      top_speed: '27 mph',
      lifespan: '55 - 70 years',
      weight: '3,000kg - 5,000kg (6,500lbs - 11,000lbs)',
      height: '2m - 3m (7ft - 10ft)'
    }
  },
  {
    name: 'Meerkat',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Carnivora',
      family: 'Herpestidae',
      genus: 'Suricata',
      scientific_name: 'Suricata suricatta'
    },
    locations: ['Africa'],
    characteristics: {
      prey: 'Insects, Rodents, Lizards',
      name_of_young: 'Kit',
      group_behavior: 'Band/Gang',
      estimated_population_size: 'Common',
      biggest_threat: 'Climate change',
      most_distinctive_feature: 'Dark bands around eyes and white face',
      other_names: 'Suricate',
      gestation_period: '11 weeks',
      habitat: 'Semi-desert and scrub-land',
      predators: 'Hawks, Jackal, Snakes',
      diet: 'Carnivore',
      average_litter_size: '3',
      lifestyle: 'Diurnal',
      common_name: 'Meerkat',
      number_of_species: '3',
      location: 'South-western Africa',
      slogan: 'One will stand on guard to watch for predators!',
      group: 'Mammal',
      color: 'BrownYellowBlackWhiteTan',
      skin_type: 'Fur',
      top_speed: '20 mph',
      lifespan: '10 - 14 years',
      weight: '600g - 975g (1.3lbs - 2.1lbs)',
      height: '25cm - 35cm (10in - 14in)',
      age_of_sexual_maturity: '1 year',
      age_of_weaning: '4 - 6 weeks'
    }
  },
  {
    name: 'Cross River Gorilla',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Primates',
      family: 'Hominidae',
      genus: 'Gorilla',
      scientific_name: 'Gorilla gorilla diehli'
    },
    locations: ['Africa'],
    characteristics: {
      main_prey: 'Leaves, Fruit, Flowers',
      habitat: 'Rainforest and dense jungle',
      predators: 'Human, Leopard, Crocodile',
      diet: 'Herbivore',
      average_litter_size: '1',
      lifestyle: 'Troop',
      favorite_food: 'Leaves',
      type: 'Mammal',
      slogan: 'Less than 300 remaining!',
      color: 'GreyBlack',
      skin_type: 'Hair',
      top_speed: '25 mph',
      lifespan: '35 - 50 years',
      weight: '100kg - 200kg (220lbs - 440lbs)',
      height: '1.4m - 1.7m (4.7ft - 5.5ft)'
    }
  },
  {
    name: 'Eastern Gorilla',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Primates',
      family: 'Hominidae',
      genus: 'Gorilla',
      scientific_name: 'Gorilla berengei'
    },
    locations: ['Africa'],
    characteristics: {
      main_prey: 'Leaves, Seeds, Herbs',
      habitat: 'Tropical forest and jungles in mountainous regions',
      predators: 'Human, Leopard',
      diet: 'Omnivore',
      average_litter_size: '1',
      lifestyle: 'Social',
      favorite_food: 'Leaves',
      type: 'Mammal',
      slogan: 'The largest primate in the world!',
      color: 'BrownGreyBlack',
      skin_type: 'Hair',
      top_speed: '25 mph',
      lifespan: '35 - 50 years',
      weight: '204kg - 227kg (450lbs - 500lbs)',
      height: '1.5m - 1.8m (5ft - 6ft)'
    }
  },
  {
    name: 'Eastern Lowland Gorilla',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Primates',
      family: 'Hominidae',
      genus: 'Gorilla',
      scientific_name: 'Gorilla Berengei Graueri'
    },
    locations: ['Africa'],
    characteristics: {
      main_prey: 'Leaves, Seeds, Herbs',
      habitat: 'Tropical forest and jungles in mountainous regions',
      predators: 'Human, Leopard',
      diet: 'Omnivore',
      average_litter_size: '1',
      lifestyle: 'Social',
      favorite_food: 'Leaves',
      type: 'Mammal',
      slogan: 'Less than 5,000 in the wild!',
      color: 'BrownGreyBlack',
      skin_type: 'Hair',
      top_speed: '25 mph',
      lifespan: '35 - 50 years',
      weight: '204kg - 227kg (450lbs - 500lbs)',
      height: '1.5m - 1.8m (5ft - 6ft)'
    }
  },
  {
    name: 'Gorilla',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Primates',
      family: 'Hominidae',
      genus: 'Gorilla'
    },
    locations: ['Africa'],
    characteristics: {
      main_prey: 'Leaves, Fruit, Flowers',
      habitat: 'Rainforest and dense jungle',
      predators: 'Human, Leopard, Crocodile',
      diet: 'Omnivore',
      average_litter_size: '1',
      lifestyle: 'Troop',
      favorite_food: 'Leaves',
      type: 'Mammal',
      slogan: "The biggest of the world's primates!",
      color: 'GreyBlack',
      skin_type: 'Hair',
      top_speed: '25 mph',
      lifespan: '35-50 years',
      weight: '100-200kg (220-440lbs)'
    }
  },
  {
    name: 'Mountain Gorilla',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Primates',
      family: 'Hominidae',
      genus: 'Gorilla',
      scientific_name: 'Gorilla Berengei Berengei'
    },
    locations: ['Africa'],
    characteristics: {
      main_prey: 'Leaves, Seeds, Herbs',
      habitat: 'Tropical forest and jungles in mountainous regions',
      predators: 'Human, Leopard',
      diet: 'Omnivore',
      average_litter_size: '1',
      lifestyle: 'Social',
      favorite_food: 'Leaves',
      type: 'Mammal',
      slogan: 'Isolated populations found in the mountains!',
      color: 'BrownGreyBlack',
      skin_type: 'Hair',
      top_speed: '25 mph',
      lifespan: '35-50 years',
      weight: '204-227kg (450-500lbs)'
    }
  },
  {
    name: 'Western Gorilla',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Primates',
      family: 'Hominidae',
      genus: 'Gorilla',
      scientific_name: 'Gorilla Gorilla'
    },
    locations: ['Africa'],
    characteristics: {
      main_prey: 'Leaves, Fruit, Flowers',
      habitat: 'Rainforest and dense jungle',
      predators: 'Human, Leopard, Crocodile',
      diet: 'Herbivore',
      average_litter_size: '1',
      lifestyle: 'Troop',
      favorite_food: 'Leaves',
      type: 'Mammal',
      slogan: 'There are two sub-species!',
      color: 'GreyBlack',
      skin_type: 'Hair',
      top_speed: '25 mph',
      lifespan: '35 - 50 years',
      weight: '100kg - 200kg (220lbs - 440lbs)',
      height: '1.4m - 1.7m (4.7ft - 5.5ft)'
    }
  },
  {
    name: 'Western Lowland Gorilla',
    taxonomy: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Primates',
      family: 'Hominidae',
      genus: 'Gorilla',
      scientific_name: 'Gorilla gorilla gorilla'
    },
    locations: ['Africa'],
    characteristics: {
      main_prey: 'Leaves, Fruit, Flowers',
      habitat: 'Rainforest and dense jungle',
      predators: 'Human, Leopard, Crocodile',
      diet: 'Herbivore',
      average_litter_size: '1',
      lifestyle: 'Troop',
      favorite_food: 'Leaves',
      type: 'Mammal',
      slogan: 'One of the great apes!',
      color: 'GreyBlack',
      skin_type: 'Hair',
      top_speed: '25 mph',
      lifespan: '35 - 50 years',
      weight: '100kg - 200kg (220lbs - 440lbs)',
      height: '1.4m - 1.7m (4.7ft - 5.5ft)'
    }
  }
]

export default animals
