const animalClasses = [
  {
    class_number: 1,
    number_of_animal_species_in_class: 41,
    class_type: 'mammal',
    class_type_de: 'Säugetier',
    animal_names: [
      'aardvark',
      'antelope',
      'bear',
      'boar',
      'buffalo',
      'calf',
      'cavy',
      'cheetah',
      'deer',
      'dolphin',
      'elephant',
      'fruitbat',
      'giraffe',
      'girl',
      'goat',
      'gorilla',
      'hamster',
      'hare',
      'leopard',
      'lion',
      'lynx',
      'mink',
      'mole',
      'mongoose',
      'opossum',
      'oryx',
      'platypus',
      'polecat',
      'pony',
      'porpoise',
      'puma',
      'pussycat',
      'raccoon',
      'reindeer',
      'seal',
      'sealion',
      'squirrel',
      'vampire',
      'vole',
      'wallaby',
      'wolf'
    ]
  },
  {
    class_number: 2,
    number_of_animal_species_in_class: 20,
    class_type: 'bird',
    class_type_de: 'Vogel',
    animal_names: [
      'chicken',
      'crow',
      'dove',
      'duck',
      'flamingo',
      'gull',
      'hawk',
      'kiwi',
      'lark',
      'ostrich',
      'parakeet',
      'penguin',
      'pheasant',
      'rhea',
      'skimmer',
      'skua',
      'sparrow',
      'swan',
      'vulture',
      'wren'
    ]
  },
  {
    class_number: 3,
    number_of_animal_species_in_class: 5,
    class_type: 'reptile',
    class_type_de: 'Reptil',
    animal_names: ['pitviper', 'seasnake', 'slowworm', 'tortoise', 'tuatara']
  },
  {
    class_number: 4,
    number_of_animal_species_in_class: 13,
    class_type: 'fish',
    class_type_de: 'Fish',
    animal_names: [
      'bass',
      'carp',
      'catfish',
      'chub',
      'dogfish',
      'haddock',
      'herring',
      'pike',
      'piranha',
      'seahorse',
      'sole',
      'stingray',
      'tuna'
    ]
  },
  {
    class_number: 5,
    number_of_animal_species_in_class: 4,
    class_type: 'amphibian',
    class_type_de: 'Amphibie',
    animal_names: ['frog', 'frog', 'newt', 'toad']
  },
  {
    class_number: 6,
    number_of_animal_species_in_class: 8,
    class_type: 'bug',
    class_type_de: 'Käfer',
    animal_names: [
      'flea',
      'gnat',
      'honeybee',
      'housefly',
      'ladybird',
      'moth',
      'termite',
      'wasp'
    ]
  },
  {
    class_number: 7,
    number_of_animal_species_in_class: 10,
    class_type: 'invertebrate',
    class_type_de: 'Wirbellose',
    animal_names: [
      'clam',
      'crab',
      'crayfish',
      'lobster',
      'octopus',
      'scorpion',
      'seawasp',
      'slug',
      'starfish',
      'worm'
    ]
  }
]

export default animalClasses
